
import React, { useState } from 'react';

interface CatalogSaveDialogProps {
  baseBranch: string;
  changedPartIds: string[];
  changeCount: number;
  onSave: (featureBranch: string, commitMessage: string, prTitle: string, prBody: string) => Promise<string>;
  onClose: () => void;
}

export const CatalogSaveDialog: React.FC<CatalogSaveDialogProps> = ({
  baseBranch,
  changedPartIds,
  changeCount,
  onSave,
  onClose,
}) => {
  const timestamp = new Date().toISOString().slice(0, 16).replace('T', '-').replace(':', '');
  const defaultBranch = `feat/${baseBranch}-catalog-edits-${timestamp}`;

  const defaultCommit =
    `chore: update catalog data\n\n` +
    changedPartIds.map((id) => `- ${id}`).join('\n');

  const defaultPRBody =
    `## Catalog Changes\n\n` +
    `${changeCount} field edit${changeCount !== 1 ? 's' : ''} across ${changedPartIds.length} part${changedPartIds.length !== 1 ? 's' : ''}:\n\n` +
    changedPartIds.map((id) => `- \`${id}\``).join('\n') +
    `\n\n---\n_Generated by Origin Hardware Architecture Studio_`;

  const [featureBranch, setFeatureBranch] = useState(defaultBranch);
  const [commitMessage, setCommitMessage] = useState(defaultCommit);
  const [prTitle, setPrTitle] = useState(`Update catalog data on ${baseBranch}`);
  const [prBody, setPrBody] = useState(defaultPRBody);
  const [isSaving, setIsSaving] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [prUrl, setPrUrl] = useState<string | null>(null);

  const handleSave = async () => {
    if (!featureBranch.trim()) { setError('Branch name is required.'); return; }
    if (!prTitle.trim()) { setError('PR title is required.'); return; }
    setIsSaving(true);
    setError(null);
    try {
      const url = await onSave(featureBranch.trim(), commitMessage, prTitle.trim(), prBody);
      setPrUrl(url);
    } catch (e: any) {
      setError(e.message || 'Save failed.');
    } finally {
      setIsSaving(false);
    }
  };

  return (
    <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4">
      <div className="bg-white rounded-2xl shadow-2xl w-full max-w-xl flex flex-col overflow-hidden">
        {/* Header */}
        <div className="px-6 py-4 border-b border-slate-200 flex items-center justify-between">
          <h2 className="font-bold text-slate-800 text-base">Save Catalog Changes</h2>
          <button onClick={onClose} disabled={isSaving} className="text-slate-400 hover:text-slate-600 p-1 rounded">
            <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M18 6 6 18"/><path d="m6 6 12 12"/></svg>
          </button>
        </div>

        {prUrl ? (
          <div className="px-6 py-8 flex flex-col items-center gap-4 text-center">
            <div className="w-12 h-12 rounded-full bg-green-100 flex items-center justify-center">
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="text-green-600"><path d="M22 11.08V12a10 10 0 1 1-5.93-9.14"/><path d="m9 11 3 3L22 4"/></svg>
            </div>
            <div>
              <p className="font-bold text-slate-800 text-base">PR Created!</p>
              <p className="text-sm text-slate-500 mt-1">Catalog updates committed and PR is open.</p>
            </div>
            <a
              href={prUrl}
              target="_blank"
              rel="noopener noreferrer"
              className="inline-flex items-center gap-2 bg-slate-900 text-white px-5 py-2.5 rounded-lg text-sm font-semibold hover:bg-slate-800 transition-colors"
            >
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="currentColor"><path d="M12 0C5.37 0 0 5.37 0 12c0 5.3 3.438 9.8 8.205 11.385.6.113.82-.258.82-.577 0-.285-.01-1.04-.015-2.04-3.338.724-4.042-1.61-4.042-1.61-.546-1.385-1.335-1.755-1.335-1.755-1.087-.744.084-.729.084-.729 1.205.084 1.838 1.236 1.838 1.236 1.07 1.835 2.809 1.305 3.495.998.108-.776.417-1.305.76-1.605-2.665-.3-5.466-1.332-5.466-5.93 0-1.31.465-2.38 1.235-3.22-.135-.303-.54-1.523.105-3.176 0 0 1.005-.322 3.3 1.23A11.52 11.52 0 0 1 12 5.803c1.02.005 2.047.138 3.006.404 2.29-1.552 3.297-1.23 3.297-1.23.645 1.653.24 2.873.12 3.176.765.84 1.23 1.91 1.23 3.22 0 4.61-2.805 5.625-5.475 5.92.42.36.81 1.096.81 2.22 0 1.606-.015 2.896-.015 3.286 0 .315.21.69.825.57C20.565 21.795 24 17.295 24 12c0-6.63-5.37-12-12-12z"/></svg>
              View Pull Request
            </a>
            <button onClick={onClose} className="text-sm text-slate-400 hover:text-slate-600">Close</button>
          </div>
        ) : (
          <div className="px-6 py-5 flex flex-col gap-5 overflow-y-auto max-h-[75vh]">
            {/* Summary */}
            <div className="bg-slate-50 rounded-lg p-3 border border-slate-200 flex items-center gap-4 text-xs">
              <span className="font-semibold text-slate-600">Changes:</span>
              <span className="text-slate-500">{changeCount} edit{changeCount !== 1 ? 's' : ''}</span>
              <span className="text-slate-500">across {changedPartIds.length} part{changedPartIds.length !== 1 ? 's' : ''}</span>
              <span className="text-slate-400 ml-auto">→ <strong>{baseBranch}</strong></span>
            </div>

            {/* Feature branch */}
            <div>
              <label className="block text-xs font-bold text-slate-500 uppercase tracking-wider mb-1.5">New Feature Branch</label>
              <input
                value={featureBranch}
                onChange={(e) => setFeatureBranch(e.target.value)}
                className="w-full text-xs border border-slate-300 rounded-lg px-3 py-2 font-mono focus:ring-2 focus:ring-blue-500 focus:outline-none"
                placeholder="feat/branch-name"
              />
              <p className="text-[10px] text-slate-400 mt-1">Will be created from <code className="bg-slate-100 px-1 rounded">{baseBranch}</code></p>
            </div>

            {/* Commit message */}
            <div>
              <label className="block text-xs font-bold text-slate-500 uppercase tracking-wider mb-1.5">Commit Message</label>
              <textarea
                value={commitMessage}
                onChange={(e) => setCommitMessage(e.target.value)}
                rows={3}
                className="w-full text-xs border border-slate-300 rounded-lg px-3 py-2 font-mono focus:ring-2 focus:ring-blue-500 focus:outline-none resize-none"
              />
            </div>

            {/* PR title */}
            <div>
              <label className="block text-xs font-bold text-slate-500 uppercase tracking-wider mb-1.5">PR Title</label>
              <input
                value={prTitle}
                onChange={(e) => setPrTitle(e.target.value)}
                className="w-full text-xs border border-slate-300 rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:outline-none"
              />
            </div>

            {/* PR body */}
            <div>
              <label className="block text-xs font-bold text-slate-500 uppercase tracking-wider mb-1.5">PR Description</label>
              <textarea
                value={prBody}
                onChange={(e) => setPrBody(e.target.value)}
                rows={6}
                className="w-full text-xs border border-slate-300 rounded-lg px-3 py-2 font-mono focus:ring-2 focus:ring-blue-500 focus:outline-none resize-y"
              />
            </div>

            {error && (
              <div className="text-xs text-red-600 bg-red-50 p-3 rounded-lg border border-red-100">{error}</div>
            )}

            {/* Actions */}
            <div className="flex gap-3 pt-1 pb-2">
              <button
                onClick={onClose}
                disabled={isSaving}
                className="flex-1 border border-slate-300 text-slate-600 hover:bg-slate-50 px-4 py-2.5 rounded-lg text-sm font-semibold transition-colors disabled:opacity-50"
              >
                Cancel
              </button>
              <button
                onClick={handleSave}
                disabled={isSaving || !featureBranch.trim()}
                className="flex-1 bg-slate-900 hover:bg-slate-800 disabled:opacity-50 disabled:cursor-not-allowed text-white px-4 py-2.5 rounded-lg text-sm font-semibold transition-colors flex items-center justify-center gap-2"
              >
                {isSaving ? (
                  <>
                    <div className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin" />
                    Saving…
                  </>
                ) : (
                  <>
                    <svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"><path d="M15 22v-4a4.8 4.8 0 0 0-1-3.5c3 0 6-2 6-5.5.08-1.25-.27-2.48-1-3.5.28-1.15.28-2.35 0-3.5 0 0-1 0-3 1.5-2.64-.5-5.36-.5-8 0C6 2 5 2 5 2c-.3 1.15-.3 2.35 0 3.5A5.403 5.403 0 0 0 4 9c0 3.5 3 5.5 6 5.5-.39.49-.68 1.05-.85 1.65-.17.6-.22 1.23-.15 1.85v4"/><path d="M9 18c-4.51 2-5-2-7-2"/></svg>
                    Save &amp; Create PR
                  </>
                )}
              </button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
};
